import { type ModelConfig } from '@/types';

export const AVAILABLE_MODELS: ModelConfig[] = [
  {
    id: 'ling-3.0-flash-free',
    name: 'Ling 3.0 Flash Free',
    provider: 'Novita AI',
    gatewayId: 'inclusionai/ling-3.0-flash-free',
  },
  {
    id: 'laguna-s-2.1-free',
    name: 'Laguna S 2.1 Free',
    provider: 'Poolside',
    gatewayId: 'poolside/laguna-s-2.1-free',
  },
  {
    id: 'laguna-s-2.1',
    name: 'Laguna S 2.1',
    provider: 'Poolside',
    gatewayId: 'poolside/laguna-s-2.1',
  },
  {
    id: 'inkling',
    name: 'Inkling',
    provider: 'Baseten, Together AI',
    gatewayId: 'thinkingmachines/inkling',
  },
  {
    id: 'seedream-5.0-pro',
    name: 'Seedream 5.0 Pro',
    provider: 'ByteDance',
    gatewayId: 'bytedance/seedream-5.0-pro',
  },
  {
    id: 'kat-coder-pro-v2.5',
    name: 'Kat Coder Pro V2.5',
    provider: 'StreamLake',
    gatewayId: 'kwaipilot/kat-coder-pro-v2.5',
  },
  {
    id: 'kat-coder-air-v2.5',
    name: 'Kat Coder Air V2.5',
    provider: 'StreamLake',
    gatewayId: 'kwaipilot/kat-coder-air-v2.5',
  },
  {
    id: 'muse-spark-1.1',
    name: 'Muse Spark 1.1',
    provider: 'Meta',
    gatewayId: 'meta/muse-spark-1.1',
  },
  {
    id: 'gpt-realtime-2.1',
    name: 'GPT Realtime 2.1',
    provider: 'OpenAI',
    gatewayId: 'openai/gpt-realtime-2.1',
  },
  {
    id: 'hy3',
    name: 'Hy3',
    provider: 'DeepInfra, Novita AI',
    gatewayId: 'tencent/hy3',
  },
  {
    id: 'fugu-ultra',
    name: 'Fugu Ultra',
    provider: 'Sakana AI',
    gatewayId: 'sakana/fugu-ultra',
  },
  {
    id: 'kimi-k2.7-code-highspeed',
    name: 'Kimi K2.7 Code Highspeed',
    provider: 'Fireworks, Moonshot AI',
    gatewayId: 'moonshotai/kimi-k2.7-code-highspeed',
  },
  {
    id: 'kimi-k2.7-code',
    name: 'Kimi K2.7 Code',
    provider: 'Fireworks, Moonshot AI',
    gatewayId: 'moonshotai/kimi-k2.7-code',
  },
  {
    id: 'nemotron-3-ultra-550b-a55b',
    name: 'Nemotron 3 Ultra 550B A55B',
    provider: 'NVIDIA',
    gatewayId: 'nvidia/nemotron-3-ultra-550b-a55b',
  },
  {
    id: 'minimax-m3',
    name: 'Minimax M3',
    provider: 'MiniMax',
    gatewayId: 'minimax/minimax-m3',
  },
  {
    id: 'step-3.7-flash',
    name: 'Step 3.7 Flash',
    provider: 'StepFun',
    gatewayId: 'stepfun/step-3.7-flash',
  },
  {
    id: 'grok-build-0.1',
    name: 'Grok Build 0.1',
    provider: 'xAI',
    gatewayId: 'xai/grok-build-0.1',
  },
  {
    id: 'recraft-v4.1-utility',
    name: 'Recraft V4.1 Utility',
    provider: 'Recraft',
    gatewayId: 'recraft/recraft-v4.1-utility',
  },
  {
    id: 'recraft-v4.1',
    name: 'Recraft V4.1',
    provider: 'Recraft',
    gatewayId: 'recraft/recraft-v4.1',
  },
  {
    id: 'gpt-realtime-whisper',
    name: 'GPT Realtime Whisper',
    provider: 'OpenAI',
    gatewayId: 'openai/gpt-realtime-whisper',
  },
  {
    id: 'gpt-realtime-2',
    name: 'GPT Realtime 2',
    provider: 'OpenAI',
    gatewayId: 'openai/gpt-realtime-2',
  },
  {
    id: 'mistral-medium-3.5',
    name: 'Mistral Medium 3.5',
    provider: 'Mistral',
    gatewayId: 'mistral/mistral-medium-3.5',
  },
  {
    id: 'mimo-v2.5-pro',
    name: 'MiMo V2.5 Pro',
    provider: 'DeepInfra, Xiaomi',
    gatewayId: 'xiaomi/mimo-v2.5-pro',
  },
  {
    id: 'mimo-v2.5',
    name: 'MiMo V2.5',
    provider: 'DeepInfra, Xiaomi',
    gatewayId: 'xiaomi/mimo-v2.5',
  },
  {
    id: 'qwen3.6-27b',
    name: 'Qwen 3.6 27B',
    provider: 'Alibaba Cloud',
    gatewayId: 'alibaba/qwen3.6-27b',
  },
  {
    id: 'qwen-3.6-max-preview',
    name: 'Qwen 3.6 Max Preview',
    provider: 'Alibaba Cloud',
    gatewayId: 'alibaba/qwen-3.6-max-preview',
  },
  {
    id: 'arrow-1.1',
    name: 'Arrow 1.1',
    provider: 'QuiverAI',
    gatewayId: 'quiverai/arrow-1.1',
  },
  {
    id: 'gemma-4-26b-a4b-it',
    name: 'Gemma 4 26B A4B IT',
    provider: 'Google Vertex AI, Novita AI, Parasail',
    gatewayId: 'google/gemma-4-26b-a4b-it',
  },
  {
    id: 'gemma-4-31b-it',
    name: 'Gemma 4 31B IT',
    provider: 'Cerebras, Novita AI, Parasail',
    gatewayId: 'google/gemma-4-31b-it',
  },
  {
    id: 'qwen3.6-plus',
    name: 'Qwen 3.6 Plus',
    provider: 'Alibaba Cloud',
    gatewayId: 'alibaba/qwen3.6-plus',
  },
  {
    id: 'glm-5v-turbo',
    name: 'GLM 5V Turbo',
    provider: 'Z.AI',
    gatewayId: 'zai/glm-5v-turbo',
  },
  {
    id: 'kat-coder-pro-v2',
    name: 'Kat Coder Pro V2',
    provider: 'StreamLake',
    gatewayId: 'kwaipilot/kat-coder-pro-v2',
  },
  {
    id: 'minimax-m2.7',
    name: 'Minimax M2.7',
    provider: 'MiniMax',
    gatewayId: 'minimax/minimax-m2.7',
  },
  {
    id: 'minimax-m2.7-highspeed',
    name: 'Minimax M2.7 Highspeed',
    provider: 'MiniMax',
    gatewayId: 'minimax/minimax-m2.7-highspeed',
  },
  {
    id: 'gpt-5.4-mini',
    name: 'GPT 5.4 Mini',
    provider: 'OpenAI',
    gatewayId: 'openai/gpt-5.4-mini',
  },
  {
    id: 'gpt-5.4-nano',
    name: 'GPT 5.4 Nano',
    provider: 'OpenAI',
    gatewayId: 'openai/gpt-5.4-nano',
  },
  {
    id: 'grok-tts',
    name: 'Grok TTS',
    provider: 'xAI',
    gatewayId: 'xai/grok-tts',
  },
  {
    id: 'grok-stt',
    name: 'Grok STT',
    provider: 'xAI',
    gatewayId: 'xai/grok-stt',
  },
  {
    id: 'glm-5-turbo',
    name: 'GLM 5 Turbo',
    provider: 'Z.AI',
    gatewayId: 'zai/glm-5-turbo',
  },
  {
    id: 'nemotron-3-super-120b-a12b',
    name: 'Nemotron 3 Super 120B A12B',
    provider: 'nvidia',
    gatewayId: 'nvidia/nemotron-3-super-120b-a12b',
  },
  {
    id: 'qwen3.5-flash',
    name: 'Qwen 3.5 Flash',
    provider: 'Alibaba Cloud',
    gatewayId: 'alibaba/qwen3.5-flash',
  },
  {
    id: 'mercury-2',
    name: 'Mercury 2',
    provider: 'inception',
    gatewayId: 'inception/mercury-2',
  },
  {
    id: 'gpt-realtime-1.5',
    name: 'GPT Realtime 1.5',
    provider: 'OpenAI',
    gatewayId: 'openai/gpt-realtime-1.5',
  },
  {
    id: 'recraft-v4',
    name: 'Recraft V4',
    provider: 'Recraft',
    gatewayId: 'recraft/recraft-v4',
  },
  {
    id: 'qwen3.5-plus',
    name: 'Qwen 3.5 Plus',
    provider: 'Alibaba Cloud',
    gatewayId: 'alibaba/qwen3.5-plus',
  },
  {
    id: 'seedream-5.0-lite',
    name: 'Seedream 5.0 Lite',
    provider: 'ByteDance',
    gatewayId: 'bytedance/seedream-5.0-lite',
  },
  {
    id: 'minimax-m2.5',
    name: 'Minimax M2.5',
    provider: 'MiniMax',
    gatewayId: 'minimax/minimax-m2.5',
  },
  {
    id: 'minimax-m2.5-highspeed',
    name: 'Minimax M2.5 Highspeed',
    provider: 'MiniMax',
    gatewayId: 'minimax/minimax-m2.5-highspeed',
  },
  {
    id: 'step-3.5-flash',
    name: 'Step 3.5 Flash',
    provider: 'StepFun',
    gatewayId: 'stepfun/step-3.5-flash',
  },
  {
    id: 'grok-imagine-image',
    name: 'Grok Imagine Image',
    provider: 'xAI',
    gatewayId: 'xai/grok-imagine-image',
  },
  {
    id: 'kimi-k2.5',
    name: 'Kimi K2.5',
    provider: 'moonshotai',
    gatewayId: 'moonshotai/kimi-k2.5',
  },
  {
    id: 'glm-4.7-flashx',
    name: 'GLM 4.7 FlashX',
    provider: 'Z.AI',
    gatewayId: 'zai/glm-4.7-flashx',
  },
  {
    id: 'glm-4.7-flash',
    name: 'GLM 4.7 Flash',
    provider: 'Z.AI',
    gatewayId: 'zai/glm-4.7-flash',
  },
  {
    id: 'voyage-4-large',
    name: 'Voyage 4 Large',
    provider: 'voyage',
    gatewayId: 'voyage/voyage-4-large',
  },
  {
    id: 'voyage-4-lite',
    name: 'Voyage 4 Lite',
    provider: 'voyage',
    gatewayId: 'voyage/voyage-4-lite',
  },
  {
    id: 'voyage-4',
    name: 'Voyage 4',
    provider: 'voyage',
    gatewayId: 'voyage/voyage-4',
  },
  {
    id: 'flux-2-klein-4b',
    name: 'Flux 2 Klein 4B',
    provider: 'bfl',
    gatewayId: 'bfl/flux-2-klein-4b',
  },
  {
    id: 'flux-2-klein-9b',
    name: 'Flux 2 Klein 9B',
    provider: 'bfl',
    gatewayId: 'bfl/flux-2-klein-9b',
  },
  {
    id: 'minimax-m2.1',
    name: 'Minimax M2.1',
    provider: 'MiniMax',
    gatewayId: 'minimax/minimax-m2.1',
  },
  {
    id: 'minimax-m2.1-lightning',
    name: 'Minimax M2.1 Lightning',
    provider: 'MiniMax',
    gatewayId: 'minimax/minimax-m2.1-lightning',
  },
  {
    id: 'glm-4.7',
    name: 'GLM 4.7',
    provider: 'Z.AI',
    gatewayId: 'zai/glm-4.7',
  },
  {
    id: 'flux-2-max',
    name: 'Flux 2 Max',
    provider: 'bfl',
    gatewayId: 'bfl/flux-2-max',
  },
  {
    id: 'nemotron-3-nano-30b-a3b',
    name: 'Nemotron 3 Nano 30B A3B',
    provider: 'nvidia',
    gatewayId: 'nvidia/nemotron-3-nano-30b-a3b',
  },
  {
    id: 'gpt-5.2',
    name: 'GPT 5.2',
    provider: 'OpenAI',
    gatewayId: 'openai/gpt-5.2',
  },
  {
    id: 'rerank-v4-fast',
    name: 'Rerank V4 Fast',
    provider: 'cohere',
    gatewayId: 'cohere/rerank-v4-fast',
  },
  {
    id: 'rerank-v4-pro',
    name: 'Rerank V4 Pro',
    provider: 'cohere',
    gatewayId: 'cohere/rerank-v4-pro',
  },
  {
    id: 'devstral-small-2',
    name: 'Devstral Small 2',
    provider: 'Mistral',
    gatewayId: 'mistral/devstral-small-2',
  },
  {
    id: 'devstral-2',
    name: 'Devstral 2',
    provider: 'Mistral',
    gatewayId: 'mistral/devstral-2',
  },
  {
    id: 'seedream-4.5',
    name: 'Seedream 4.5',
    provider: 'ByteDance',
    gatewayId: 'bytedance/seedream-4.5',
  },
  {
    id: 'mistral-large-3',
    name: 'Mistral Large 3',
    provider: 'Mistral',
    gatewayId: 'mistral/mistral-large-3',
  },
  {
    id: 'nova-2-lite',
    name: 'Nova 2 Lite',
    provider: 'amazon',
    gatewayId: 'amazon/nova-2-lite',
  },
  {
    id: 'ministral-14b',
    name: 'Ministral 14B',
    provider: 'Mistral',
    gatewayId: 'mistral/ministral-14b',
  },
  {
    id: 'trinity-mini',
    name: 'Trinity Mini',
    provider: 'Arcee AI',
    gatewayId: 'arcee-ai/trinity-mini',
  },
  {
    id: 'flux-2-pro',
    name: 'Flux 2 Pro',
    provider: 'bfl',
    gatewayId: 'bfl/flux-2-pro',
  },
  {
    id: 'flux-2-flex',
    name: 'Flux 2 Flex',
    provider: 'bfl',
    gatewayId: 'bfl/flux-2-flex',
  },
  {
    id: 'grok-4.1-fast-non-reasoning',
    name: 'Grok 4.1 Fast Non Reasoning',
    provider: 'xAI',
    gatewayId: 'xai/grok-4.1-fast-non-reasoning',
  },
  {
    id: 'grok-4.1-fast-reasoning',
    name: 'Grok 4.1 Fast Reasoning',
    provider: 'xAI',
    gatewayId: 'xai/grok-4.1-fast-reasoning',
  },
  {
    id: 'gpt-5.1-codex-max',
    name: 'GPT 5.1 Codex Max',
    provider: 'OpenAI',
    gatewayId: 'openai/gpt-5.1-codex-max',
  },
  {
    id: 'gpt-5.1-instant',
    name: 'GPT 5.1 Instant',
    provider: 'OpenAI',
    gatewayId: 'openai/gpt-5.1-instant',
  },
  {
    id: 'gpt-5.1-codex-mini',
    name: 'GPT 5.1 Codex Mini',
    provider: 'OpenAI',
    gatewayId: 'openai/gpt-5.1-codex-mini',
  },
  {
    id: 'gpt-5.1-codex',
    name: 'GPT 5.1 Codex',
    provider: 'OpenAI',
    gatewayId: 'openai/gpt-5.1-codex',
  },
  {
    id: 'kat-coder-pro-v1',
    name: 'Kat Coder Pro V1',
    provider: 'StreamLake',
    gatewayId: 'kwaipilot/kat-coder-pro-v1',
  },
  {
    id: 'gpt-oss-safeguard-20b',
    name: 'GPT OSS Safeguard 20B',
    provider: 'OpenAI',
    gatewayId: 'openai/gpt-oss-safeguard-20b',
  },
  {
    id: 'nemotron-nano-12b-v2-vl',
    name: 'Nemotron Nano 12B V2 VL',
    provider: 'nvidia',
    gatewayId: 'nvidia/nemotron-nano-12b-v2-vl',
  },
  {
    id: 'minimax-m2',
    name: 'Minimax M2',
    provider: 'MiniMax',
    gatewayId: 'minimax/minimax-m2',
  },
  {
    id: 'gpt-realtime-mini',
    name: 'GPT Realtime Mini',
    provider: 'OpenAI',
    gatewayId: 'openai/gpt-realtime-mini',
  },
  {
    id: 'interfaze-beta',
    name: 'Interfaze Beta',
    provider: 'interfaze',
    gatewayId: 'interfaze/interfaze-beta',
  },
  {
    id: 'gpt-image-1-mini',
    name: 'GPT Image 1 Mini',
    provider: 'OpenAI',
    gatewayId: 'openai/gpt-image-1-mini',
  },
  {
    id: 'glm-4.6',
    name: 'GLM 4.6',
    provider: 'Z.AI',
    gatewayId: 'zai/glm-4.6',
  },
  {
    id: 'glm-4.6v',
    name: 'GLM 4.6V',
    provider: 'Z.AI',
    gatewayId: 'zai/glm-4.6v',
  },
  {
    id: 'glm-4.6v-flash',
    name: 'GLM 4.6V Flash',
    provider: 'Z.AI',
    gatewayId: 'zai/glm-4.6v-flash',
  },
  {
    id: 'gemini-2.5-flash-preview-09-2025',
    name: 'Gemini 2.5 Flash Preview 09 2025',
    provider: 'google',
    gatewayId: 'google/gemini-2.5-flash-preview-09-2025',
  },
  {
    id: 'qwen3-vl-235b-a22b-instruct',
    name: 'Qwen 3 VL 235B A22B Instruct',
    provider: 'Alibaba Cloud',
    gatewayId: 'alibaba/qwen3-vl-235b-a22b-instruct',
  },
];

/** IDs of models selected by default on first load */
export const DEFAULT_SELECTED_MODEL_IDS = ['gpt-5.4-mini', 'mimo-v2.5', 'muse-spark-1.1'];

/** Look up a model by its internal ID */
export function getModelById(id: string): ModelConfig | undefined {
  return AVAILABLE_MODELS.find((m) => m.id === id);
}

/** Look up a model by its gateway ID */
export function getModelByGatewayId(gatewayId: string): ModelConfig | undefined {
  return AVAILABLE_MODELS.find((m) => m.gatewayId === gatewayId);
}
